public class CalculatorClass {
    
    public static Void Addition()
    {
        Integer a = 10,b = 5;
        Integer add = a+b;
        System.debug('Addition of a and b is' +add);
    }
      public static Void Substraction()
    {
        Integer a = 10,b = 5;
        Integer sub = a-b;
        System.debug('Substraction of a and b is' +sub);
    }
      public static Void Multiplication()
    {
        Integer a = 10,b = 5;
        Integer mul = a*b;
        System.debug('Multiplication of a and b is' +mul);
    }
      public static Void Division()
    {
        Integer a = 10,b = 5;
        Integer div = a/b;
        System.debug('Division of a and b is' +div);
    }

}