Public class myfirstclass{
    
    //class variable
    public integer A = 5; //Variable Asssignment
    Integer Y = 10;
    Private Integer R; //Varible
    
    //Method 1
    Public  void CalculateArea(Integer L,Integer B) //Instance Variable
    {
        Integer Result;
        Result = L*B;
        System.debug(Result);
        
    }
    //Method 2
    Public void CalculateArea2(Integer L,Integer B)  //Instance Variable..
    {
        Integer Result;
        Result = L*B;
        System.debug(Result);
    }
}